### ISSUE TITLE
Option to edit and delete existing reminders. 

### ISSUE THREAD

**Issue by alltrust** [alltrust/Reminder-App#12]
https://github.com/alltrust/Reminder-App/blob/3a11f9ca618928992499d718cb6c1e02725697c6/.github/ISSUE_TEMPLATE/update-and-delete-features.md

**Comment by sebastianserrano** [comment]
Be more specific. https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
