### ISSUE TITLE
"removeReminder" In Place Updates

### ISSUE THREAD

**Issue by sebastianserrano** [alltrust/Reminder-App#4]
Don't mutate existing state, generate a new one. https://medium.com/@kkranthi438/dont-mutate-state-in-react-6b25d5e06f42
https://github.com/alltrust/Reminder-App/blob/628a2d8c14e37277dc36ce95243ad413ef014cd7/src/store/reminders.js#L43

**Comment by alltrust** [comment]
I'll change the name as it not much remove the reminder from the original array, but changing its completionStatus from false to true.

**Comment by sebastianserrano** [comment]
> I'll change the name as it not much remove the reminder from the original array

 my comment wasn't about naming, it was about state management

> changing its completionStatus from false to true.

even `completionStatus` set to a `Boolean` doesn't make much sense. `completed` would be more appropriate to a `Boolean` value. Though, even better would be to have make it an `enum`. 

```ts
enum CompletedStatus {
  completed = 'Completed',
  incomplete = 'Incomplete'
}

type Status = CompletedStatus


```

**Comment by alltrust** [comment]
#9
